USE finalProjectTables;
GO;
ALTER TABLE Clients WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_LocationID FOREIGN KEY(LocationID) REFERENCES Locations(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_ClientID FOREIGN KEY(ClientID) REFERENCES Clients(ClientID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetails
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE OrderDetails
ADD CONSTRAINT FK_Stock# FOREIGN KEY(Stock#) REFERENCES Stock(StockID)
ON UPDATE CASCADE
GO


